echo off

:: Increment the build number.
:: Reads the build number from a one line DOS command called getBuildNumber,
:: then increments the number, and rewrites the DOS command.

:: Read %buildnumber%;  This file is where the buildnumber is incremented and stored.
call BuildNumber_Get.cmd

:: write the header file
echo //This file is automatically generated by LRT's build script. > %1
echo #define kBuildNumber %buildnumber% >> %1

:: Increment the buildnumber
echo set /a buildnumber=%buildnumber%+1 > BuildNumber_Get.cmd

type buildnumber.h